
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CONTACTDATA_START = 'CONTACTDATA_START';
export const CONTACTDATA_SUCCESS = 'CONTACTDATA_SUCCESS';
export const CONTACTDATA_FAIL = 'CONTACTDATA_FAIL';

